[package]
name="latte-headless"
version.workspace=true
edition.workspace=true
license.workspace=true
repository.workspace=true
rust-version.workspace=true
[dependencies]
latte-core.workspace=true
latte-engine.workspace=true
uuid.workspace=true
tokio.workspace=true
serde.workspace=true
serde_json.workspace=true
thiserror.workspace=true
reqwest.workspace=true
sha2.workspace=true
json5.workspace=true
[lints]
workspace=true
[dev-dependencies]
tempfile.workspace=true
rusqlite.workspace=true
